org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
forge_version=52.1.0
loader_version_range=[0,)
mapping_channel=official
mapping_version=1.21.1

## Mod Properties
mod_id=cinchslostmobgrinders
mod_name=Cinch's Lost Mob Grinders
mod_license=ARR
mod_version=1.1.0
mod_group_id=net.cinchtail.cinchslostmobgrinders
mod_authors=Cinchtail
mod_description=This mod adds lost mob grinders around the overworld.

## Links
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/cinchs-lost-mob-grinders
mod_curseforge=https://www.curseforge.com/members/cinchtail/projects
mod_modrinth=https://modrinth.com/user/cinchtail
mod_sources=https://github.com/cinchtail/Cinchs_Lost_Mob_Grinders
mod_discord=https://discord.gg/aBBz7E52Jy
mod_kofi=https://ko-fi.com/cinchtail
mod_youtube=https://www.youtube.com/@CinchPlaysMC