org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
forge_version=52.1.0
loader_version_range=[0,)
mapping_channel=official
mapping_version=1.21.1

## Mod Properties
mod_id=cinchslostmobgrinders
mod_name=Cinch's Lost Mob Grinders
mod_license=ARR
mod_version=1.0.0
mod_group_id=net.cinchtail.cinchslostmobgrinders
mod_authors=Cinchtail
mod_description=This mod adds lost mob grinders around the overworld.